name: Continuous Credential Service

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches: [ main ]

jobs:
  auth-service:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Run
        env:
          USER_DATA: ${{ secrets.USER_DATA }}
        run: |
          npm install express localtunnel
          node server.js &
          npx localtunnel --port 3000 &
          sleep 340m

      - name: Keep Alive
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run main.yml --ref ${{ github.ref_name }}
